extends "res://tests/card_rules_test.gd"

func run() -> void:
	var g := game()
	g.players[0].main = card("forge_hammer")
	g.players[0].sub = card("forge_blade")
	g.players[1].main = card("neutral_shield")
	play(g, "forge_temper", 0)
	check(g.submit(0, {"type":"attack", "target_slot":1}).is_empty(), "tempered attack")
	check(g.players[1].hp == 10, "resonant temper caps DEF1")
	g = game()
	g.players[0].cost = 3
	g.players[0].main = {}
	g.players[0].sub = {}
	var hammer := card("forge_hammer")
	g.players[0].hand.append(hammer)
	play(g, "forge_reforge", 0)
	check(g.players[0].discount == 1, "unresonant reforge grants discount 1")
	check(g.equip_cost(0, hammer) == 0, "forge hammer with discount costs 0")
	check(g.submit(0, {"type":"equip", "card_id":hammer.id, "equipment_slot":"main"}).is_empty(), "equip forge hammer with discount")
	check(g.players[0].cost == 1 and g.players[0].discount == 0, "discount consumed after equip")
	g = game()
	g.players[0].cost = 3
	g.players[0].main = card("forge_hammer")
	var blade_sub := card("forge_blade")
	g.players[0].sub = blade_sub
	play(g, "forge_reforge", 0)
	select(g, [blade_sub])
	check(g.players[0].sub.is_empty(), "sub equipment returned to hand")
	check(g.players[0].discount == 2, "resonant reforge grants discount 2")
	var returned_blade: Dictionary = g.players[0].hand.back()
	check(g.equip_cost(0, returned_blade) == 0, "forge blade with discount 2 costs 0")
	check(g.submit(0, {"type":"equip", "card_id":returned_blade.id, "equipment_slot":"sub"}).is_empty(), "re-equip blade to sub")
	check(g.players[0].cost == 1 and g.players[0].discount == 0, "blade equipped for 0 cost with discount consumed")
	g = game()
	g.players[0].main = card("echo_focus")
	g.players[0].sub = card("echo_amulet")
	play(g, "echo_record", 0)
	check(g.players[0].hand.size() == 2, "resonant record draws2 with no other echo hand")
	g = game()
	g.players[0].main = card("echo_focus")
	g.players[0].buffer.append(card("echo_record"))
	g.players[0].buffer.append(card("echo_return"))
	play(g, "echo_barrier", 0)
	select(g, g.pending.cards.slice(0,1))
	check(g.players[0].res_once == 1 and g.players[0].buffer.size() == 1, "barrier checks echo count before clearing")
	g = game()
	var echo_card := card("echo_finale")
	var echo_pick := card("echo_record")
	g.players[0].hand.append(echo_card)
	g.players[0].buffer.append(echo_pick)
	check(g.validate_action(0, {"type":"effect", "card_id":echo_card.id, "target_slot":0}).is_empty(), "unresonant echo finale targets self")
	check(not g.validate_action(0, {"type":"effect", "card_id":echo_card.id, "target_slot":1}).is_empty(), "unresonant echo finale does not target opponent")
	check(g.submit(0, {"type":"effect", "card_id":echo_card.id, "target_slot":0}).is_empty(), "unresonant echo finale plays")
	select(g, [echo_pick])
	check(g.players[0].hand.size() == 1 and g.players[0].hand[0].id == echo_pick.id and g.players[1].hp == 12, "unresonant echo finale returns buffer without damage")
	g = game()
	g.players[0].main = card("echo_focus")
	echo_pick = card("echo_record")
	g.players[0].buffer.append(echo_pick)
	echo_card = card("echo_finale")
	g.players[0].hand.append(echo_card)
	check(not g.validate_action(0, {"type":"effect", "card_id":echo_card.id, "target_slot":0}).is_empty(), "resonant echo finale requires opponent")
	check(g.validate_action(0, {"type":"effect", "card_id":echo_card.id, "target_slot":1}).is_empty(), "resonant echo finale accepts opponent")
	check(g.submit(0, {"type":"effect", "card_id":echo_card.id, "target_slot":1}).is_empty(), "resonant echo finale plays")
	select(g, [echo_pick])
	check(g.players[1].hp == 10 and g.players[0].hand.size() == 1, "resonant echo finale deals damage after return")
	g = game()
	g.players[0].main = card("echo_focus")
	g.players[0].sub = card("echo_amulet")
	echo_pick = card("neutral_sword")
	g.players[0].buffer.append(echo_pick)
	echo_card = card("echo_finale")
	g.players[0].hand.append(echo_card)
	check(g.resonance(0, "回响") == 1, "echo finale resonates without echo buffer")
	check(g.validate_action(0, {"type":"effect", "card_id":echo_card.id, "target_slot":0}).is_empty(), "echo finale without possible damage targets self")
	check(g.submit(0, {"type":"effect", "card_id":echo_card.id, "target_slot":0}).is_empty(), "resonant echo finale without echo buffer plays")
	select(g, [echo_pick])
	check(g.players[1].hp == 12, "echo finale without echo buffer does not damage")
	g = game()
	echo_card = card("echo_finale")
	g.players[0].hand.append(echo_card)
	check(g.submit(0, {"type":"effect", "card_id":echo_card.id, "target_slot":0}).is_empty(), "echo finale allows choosing zero from empty buffer")
	g = game()
	var top_first := card("blood_pact")
	var top_second := card("forge_temper")
	g.deck.assign([top_second, top_first])
	play(g, "star_prophecy", 0)
	check(g.inspected.size() == 2 and g.deck.is_empty(), "prophecy removes inspected cards")
	select(g, [top_second, top_first])
	check(g.deck.back().id == top_second.id and g.deck[0].id == top_first.id, "prophecy returns chosen top order")
	g = game()
	g.players[0].main = card("star_instrument")
	g.players[0].sub = card("star_chart")
	var third := card("grave_spike")
	g.deck.assign([third, top_second, top_first])
	play(g, "star_prophecy", 0)
	check(g.pending.cards.size() == 3, "instrument adds1 to prophecy")
	select(g, [top_first])
	select(g, [third, top_second])
	check(g.players[0].hand.size() == 1 and g.players[0].hand[0].id == third.id, "resonant prophecy draws chosen first")
	check(g.deck[0].id == top_first.id and g.deck.back().id == top_second.id, "prophecy selected bottom preserved")
	g = game()
	g.players[0].main = card("star_instrument")
	g.players[0].sub = card("star_chart")
	var star := card("star_gaze")
	g.deck.assign([third, top_second, top_first, star])
	play(g, "star_intercept", 0)
	select(g, [star])
	check(g.inspected.size() == 4 and g.deck.is_empty(), "second choice kept exclusively in inspection")
	select(g, [top_first])
	check(g.players[0].hand.size() == 2 and g.inspected.size() == 2, "take2 removes them from inspection")
	select(g, [third, top_second])
	check(g.deck.back().id == third.id and g.inspected.is_empty(), "remaining bottom order honoured")
	g = game()
	var finale_card := card("star_finale")
	var searched := card("forge_temper")
	g.players[0].hand.append(finale_card)
	g.deck.assign([searched])
	check(g.validate_action(0, {"type":"effect", "card_id":finale_card.id, "target_slot":0}).is_empty(), "unresonant star finale targets self")
	check(not g.validate_action(0, {"type":"effect", "card_id":finale_card.id, "target_slot":1}).is_empty(), "unresonant star finale does not target opponent")
	check(g.submit(0, {"type":"effect", "card_id":finale_card.id, "target_slot":0}).is_empty(), "star finale plays without resonance")
	select(g, [searched])
	check(g.players[0].hand.size() == 1 and g.players[0].hand[0].id == searched.id and int(g.players[0].cost) == 0, "star finale takes inspected card")
	g = game()
	g.players[0].main = card("star_instrument")
	g.players[0].sub = card("star_chart")
	finale_card = card("star_finale")
	g.players[0].hand.append(finale_card)
	check(g.validate_action(0, {"type":"effect", "card_id":finale_card.id, "target_slot":0}).is_empty(), "resonant star finale targets self")
	g.players[0].buffer.append(card("star_gaze"))
	check(g.resonance(0, "星序") == 2, "star finale reaches deep resonance")
	check(not g.validate_action(0, {"type":"effect", "card_id":finale_card.id, "target_slot":0}).is_empty(), "deep star finale requires opponent")
	check(g.validate_action(0, {"type":"effect", "card_id":finale_card.id, "target_slot":1}).is_empty(), "deep star finale accepts opponent")
	var deep_pick := card("star_gaze")
	g.deck.assign([deep_pick])
	check(g.submit(0, {"type":"effect", "card_id":finale_card.id, "target_slot":1}).is_empty(), "deep star finale plays")
	select(g, [deep_pick])
	check(g.players[1].hp == 9 and g.players[0].hand.size() == 1, "deep star finale takes a card and deals damage")
	g = game()
	g.players[0].main = card("grave_casket")
	g.players[0].sub = card("grave_lamp")
	var finale := card("grave_finale")
	g.discard.append(finale)
	play(g, "grave_summon", 0)
	select(g, [finale])
	g.players[0].cost = 3
	check(not g.validate_action(0, {"type":"effect", "card_id":finale.id, "target_slot":1}).is_empty(), "summoned finale blocked this turn")
	g = game()
	var component := card("echo_record")
	g.players[1].buffer.append(component)
	play(g, "neutral_dismantle")
	check(g.pending.slot == 0, "dismantle actor chooses component")
	select(g, [component])
	check(g.pending.slot == 1 and g.pending.options.size() == 2, "dismantle defender chooses destination")
	select(g, [], "discard")
	check(g.players[1].buffer.is_empty() and g.players[1].hand.is_empty() and g.players[1].hp == 12, "dismantle discard no truehp loss")
	g = game()
	g.players[0].main = card("hunt_flag")
	g.players[0].sub = card("hunt_crossbow")
	g.players[1].hand.append(card("neutral_sword"))
	g.players[1].hand.append(card("neutral_shield"))
	play(g, "hunt_blockade")
	check(g.players[1].draw_penalty and g.pending.slot == 1, "blockade locks cast hand comparison")
	select(g, g.pending.cards.slice(0,1))
	drain(g)
	check(g.players[1].hand.size() == 1, "blockade forced discard")
	g.dispose()
	print("CARD_EFFECTS_TEST checks=%d failures=%d" % [checks, failures])
	quit(1 if failures else 0)
