extends "res://tests/card_rules_test.gd"

func setup_plan(g: CardRules, id: String) -> Dictionary:
	var c := card(id)
	g.players[0].hand.append(c)
	check(g.submit(0, {"type":"plan", "card_id":c.id}).is_empty(), "set " + id)
	return c

func begin(g: CardRules, slot: int = 0) -> void:
	g.current = slot
	g._begin_turn(slot)
	g._drain()

func resonant(g: CardRules, level: int = 1, main_id: String = "scheme_hourglass") -> void:
	g.players[0].main = card(main_id)
	g.players[0].sub = card("scheme_lamp" if main_id == "scheme_hourglass" else "scheme_hourglass") if level > 0 else {}
	if level == 2: g.players[0].buffer.append(card("scheme_insight"))

func restrictions() -> void:
	var g := game()
	var supply := card("scheme_supply")
	g.players[0].hand.append(supply)
	check(not g.submit(0, {"type":"plan", "card_id":supply.id}).is_empty(), "requires scheme main")
	g.players[0].sub = card("scheme_lamp")
	check(not g.submit(0, {"type":"plan", "card_id":supply.id}).is_empty(), "sub cannot enable planning")
	g.players[0].main = card("scheme_lamp")
	for id in ["scheme_lamp", "scheme_counter", "neutral_meditate", "forge_temper"]:
		var c := card(id)
		g.players[0].hand.append(c)
		check(not g.validate_action(0, {"type":"plan", "card_id":c.id}).is_empty(), "reject non-plan card " + id)
	g.players[0].blocked.append(supply.id)
	check(not g.validate_action(0, {"type":"plan", "card_id":supply.id}).is_empty(), "blocked retrieval cannot plan")
	g.players[0].blocked.clear()
	g.players[0].cost = 0
	g.players[0].discount = 3
	check(not g.validate_action(0, {"type":"plan", "card_id":supply.id}).is_empty(), "no planning discount")
	g.players[0].cost = 3
	var hand_size: int = g.players[0].hand.size()
	check(g.submit(0, {"type":"plan", "card_id":supply.id, "target_slot":99}).is_empty(), "setting has no target")
	check(g.players[0].cost == 2 and g.players[0].hand.size() == hand_size - 1 and g.pending.is_empty(), "pay once without immediate draw or response")
	check(g.players[0].plan.id == supply.id and g.resonance(0, "伏谋") == 0, "plan independent of resonance")
	check(not g.submit(0, {"type":"plan", "card_id":supply.id}).is_empty(), "one planning per turn")
	check(not g.submit(1, {"type":"cancel_plan"}).is_empty(), "off-turn cannot cancel")
	check(g.submit(0, {"type":"cancel_plan"}).is_empty(), "cancel newly set plan")
	check(g.players[0].plan.is_empty() and g.players[0].cost == 2 and g.players[0].plan_used and g.discard.back().id == supply.id, "cancel no refund or reset")
	supply = card("scheme_supply")
	g.players[0].hand.append(supply)
	check(not g.validate_action(0, {"type":"plan", "card_id":supply.id}).is_empty(), "cannot plan after cancellation")
	check(not g.submit(0, {"type":"cancel_plan"}).is_empty(), "cannot cancel empty slot")
	g.dispose()

func timing_and_targets() -> void:
	var g := game()
	resonant(g, 0)
	var c := setup_plan(g, "scheme_detonate")
	check(g.players[1].hp == 12 and g.pending.is_empty(), "damage plan has no immediate effect")
	check(g.submit(0, {"type":"end_turn"}).is_empty(), "wait through opponent turn")
	check(g.players[0].plan.id == c.id and g.current == 1, "other turn does not execute plan")
	check(g.submit(1, {"type":"end_turn"}).is_empty(), "own turn automatically executes")
	check(g.pending.get("kind") == "plan_target" and g.players[0].hand.size() == 2 and g.players[0].cost == 3, "target choice after preparation draw/reset")
	check(not g.players[0].plan_used, "own turn resets planning allowance")
	for action in [{"type":"swap_equipment"}, {"type":"draw_two"}, {"type":"prepare"}, {"type":"attack", "target_slot":1}, {"type":"cancel_plan"}, {"type":"end_turn"}]:
		check(not g.validate_action(0, action).is_empty(), "normal action blocked before execution " + action.type)
	check(not g.submit(1, {"type":"choose", "option":"1"}).is_empty(), "only planner chooses target")
	check(not g.submit(0, {"type":"choose", "option":"0"}).is_empty(), "cannot target self")
	check(not g.submit(0, {"type":"choose", "option":"99"}).is_empty(), "cannot target missing player")
	select(g, [], "1")
	check(g.players[0].plan.is_empty() and not g.find(g.resolving, c.id).is_empty(), "plan moves to resolving before buffering")
	drain(g)
	check(g.players[1].hp == 10 and g.players[0].cost == 3 and not g.find(g.discard, c.id).is_empty(), "execute base damage without second payment")
	check(g.submit(0, {"type":"plan", "card_id":setup_hand(g, "scheme_supply").id}).is_empty(), "may plan again after execution")
	g.dispose()

func setup_hand(g: CardRules, id: String, slot: int = 0) -> Dictionary:
	var c := card(id)
	g.players[slot].hand.append(c)
	return c

func resonance_and_equipment() -> void:
	var g := game()
	resonant(g, 0, "scheme_lamp")
	setup_plan(g, "scheme_detonate")
	check(g.players[0].hand.is_empty() and not g.players[0].used.has("scheme_lamp"), "plan cannot turn on lamp resonance")
	g.players[0].sub = card("scheme_hourglass")
	begin(g)
	select(g, [], "1")
	check(g.players[1].hp == 8 and g.players[0].hand.size() == 2, "resonance checked at execution, lamp not retriggered")
	g.dispose()
	g = game()
	resonant(g, 2)
	setup_plan(g, "scheme_finale")
	g.players[0].main = card("neutral_sword")
	g.deck.assign([card("scheme_lamp"), card("scheme_hourglass")])
	begin(g)
	check(g.pending.kind == "plan_target" and g.players[0].hand[0].base_id == "scheme_hourglass", "freshly drawn main cannot be equipped before plan")
	check(not g.submit(0, {"type":"equip", "card_id":g.players[0].hand[0].id}).is_empty(), "preparation draw cannot repair resonance before execution")
	select(g, [], "1")
	check(g.players[1].hp == 10 and g.players[0].hand.size() == 2, "lost main still executes base without deep draw")
	g.dispose()
	g = game()
	resonant(g, 2)
	var c := setup_plan(g, "scheme_finale")
	var counter := setup_hand(g, "echo_counter", 1)
	begin(g)
	select(g, [], "1")
	check(g.pending.kind == "counter" and g.players[0].used.has("scheme_hourglass"), "hourglass consumed before response")
	# Alter components during the response window to verify the locked context.
	g.discard.append(g.players[0].sub)
	g.players[0].sub = {}
	g.discard.append_array(g.players[0].buffer)
	g.players[0].buffer.clear()
	select(g, [counter])
	check(g.players[1].hp == 8 and g.players[0].hand.size() == 4, "locked deep resonance and hourglass survive component removal")
	check(g.resolving.is_empty() and g.find(g.discard, c.id).size() > 0, "plan finalized once after response")
	g.dispose()
	g = game()
	resonant(g, 1)
	setup_plan(g, "scheme_detonate")
	g.players[1].main = card("star_chart")
	g.players[1].sub = card("star_instrument")
	g.players[1].res_once = 3
	var blocked_counter := setup_hand(g, "star_counter", 1)
	begin(g)
	select(g, [], "1")
	select(g, [blocked_counter])
	drain(g)
	check(g.players[1].hp == 12 and g.players[0].used.has("scheme_hourglass"), "completely blocked plan keeps hourglass use consumed")
	g.dispose()
	g = game()
	resonant(g, 1, "scheme_lamp")
	setup_plan(g, "scheme_supply")
	check(g.players[0].hand.size() == 1 and g.players[0].used.has("scheme_lamp"), "lamp draws once when resonant plan is set")
	check(g.submit(0, {"type":"cancel_plan"}).is_empty(), "cancel resonant supply")
	check(g.players[0].used.has("scheme_lamp"), "cancel does not refund equipment use")
	begin(g)
	setup_plan(g, "scheme_supply")
	check(g.players[0].hand.size() == 4, "lamp resets next own turn")
	g.dispose()

func card_branches() -> void:
	for level in [0, 1, 2]:
		for planned in [false, true]:
			var g := game()
			resonant(g, level, "scheme_lamp")
			if planned:
				setup_plan(g, "scheme_finale")
				begin(g)
				select(g, [], "1")
			else: play(g, "scheme_finale", 1)
			check(g.players[1].hp == 12 - (2 if level == 0 else (4 if planned else 3)), "finale branch damage level%d planned%s" % [level, planned])
			var expected_draws: int = (2 if planned else 0) + (1 if planned and level > 0 else 0) + ((2 if planned else 1) if level == 2 else 0)
			check(g.players[0].hand.size() == expected_draws, "finale deep draws level%d planned%s" % [level, planned])
			g.dispose()
	for level in [0, 1]:
		var g := game()
		resonant(g, level)
		setup_plan(g, "scheme_supply")
		begin(g)
		check(g.pending.is_empty() and g.players[0].hand.size() == 2 + (2 if level > 0 else 1), "planned supply draw count")
		check(not g.players[0].used.has("scheme_hourglass"), "supply does not consume hourglass")
		g.dispose()
	var g := game()
	resonant(g, 1)
	setup_plan(g, "scheme_blade")
	begin(g)
	check(g.submit(0, {"type":"end_turn"}).is_empty() and g.players[0].attack_mods.is_empty(), "unused planned attack buff expires at turn end")
	g.dispose()

func immediate_resources() -> void:
	for level in [0, 1]:
		var g := game()
		resonant(g, level)
		play(g, "scheme_supply", 0)
		if level > 0:
			check(g.pending.cards.size() == 1 and g.pending.min == 0, "immediate supply offers optional hand cycle")
			var cycled: Dictionary = g.pending.cards[0]
			select(g, [cycled])
			check(g.deck[0].id == cycled.id, "immediate supply places chosen card on bottom")
		check(g.players[0].hand.size() == 1 and g.players[0].cost == 2 and g.players[0].plan.is_empty(), "immediate supply never sets plan")
		g.dispose()
		g = game()
		resonant(g, level)
		var pick := card("scheme_supply")
		g.deck.assign([card("neutral_sword"), card("neutral_sword"), pick])
		play(g, "scheme_insight", 0)
		check(g.inspected.size() == (3 if level > 0 else 2) and g.pending.cards.size() == 1, "immediate insight inspects2/3 but still requires scheme card")
		select(g, [pick])
		drain(g)
		check(g.players[0].hand.size() == 1 and g.players[0].plan.is_empty(), "immediate insight only takes legal card")
		g.dispose()
		g = game()
		resonant(g, level)
		setup_plan(g, "scheme_blade")
		begin(g)
		check(g.pending.is_empty() and g.players[0].attack_mods.scheme_blade.atk == (3 if level > 0 else 1), "blade executes without damage response")
		check(not g.players[0].used.has("scheme_hourglass"), "blade does not consume damage bonus")
		g.players[0].cost = 3
		play(g, "scheme_blade", 0)
		check(g.players[0].attack_mods.scheme_blade.atk == (3 if level > 0 else 1), "same-name attack buff keeps higher")
		g.players[1].main = card("neutral_shield")
		var counter := setup_hand(g, "forge_counter", 1)
		check(g.submit(0, {"type":"attack", "target_slot":1}).is_empty() and g.pending.kind == "counter", "subsequent attack opens own counter window")
		select(g, [counter])
		check(g.players[1].hp == (10 if level > 0 else 12), "planned blade DEF cap and normal reduction")
		check(g.players[0].attack_used and g.players[0].attack_mods.is_empty(), "normal attack limit consumes planned buff")
		g.dispose()

func inspect_boundaries() -> void:
	for level in [0, 1]:
		var g := game()
		resonant(g, level)
		setup_plan(g, "scheme_insight")
		var first := card("neutral_sword")
		var second := card("scheme_supply")
		var third := card("forge_temper")
		var fourth := card("scheme_blade")
		g.deck.assign([fourth, third, second, first, card("neutral_shield"), card("neutral_shield")])
		begin(g)
		check(g.inspected.size() == (4 if level > 0 else 2), "planned inspect count respects resonance")
		check(g.pending.cards.size() == (4 if level > 0 else 1), "planned inspect eligible cards")
		select(g, [first if level > 0 else second])
		drain(g)
		check(g.inspected.is_empty() and g.players[0].hand.size() == 3, "inspection adds one and orders remaining bottom")
		g.dispose()
	var g := game()
	resonant(g, 0)
	setup_plan(g, "scheme_insight")
	g.deck.assign([card("neutral_sword"), card("neutral_sword"), card("neutral_sword")])
	begin(g)
	check(g.pending.is_empty() and g.players[0].hand.size() == 2 and g.deck.size() == 1, "short inspection no matching card and no shuffle")
	g.dispose()

func counter_retrieval() -> void:
	var g := game()
	resonant(g, 1)
	var c := setup_plan(g, "scheme_detonate")
	var response := setup_hand(g, "scheme_counter")
	g.current = 1
	g.players[1].main = card("neutral_sword")
	g.attack_buff(1, "test", {"atk":5})
	check(g.submit(1, {"type":"attack", "target_slot":0}).is_empty(), "incoming damage opens scheme response")
	select(g, [response])
	select(g, [], "enhanced")
	check(g.players[0].plan.is_empty() and g.find(g.pending.cards, c.id).id == c.id, "returned plan available to subsequent buffer")
	select(g, [c])
	check(g.players[0].hp == 11 and g.players[0].cost == 0 and g.players[0].counter_used, "retrieve reduces3, then normal buffer, no cost refund")
	check(g.players[0].plan_used and g.players[0].plan_due == 0, "retrieval cancels due without resetting allowance")
	begin(g)
	check(g.players[1].hp == 12 and g.players[0].plan.is_empty(), "retrieved plan never executes")
	g.dispose()
	# The enhanced return is optional; without a plan the base counter still works.
	for keep_plan in [false, true]:
		g = game()
		resonant(g, 1)
		if keep_plan: setup_plan(g, "scheme_supply")
		response = setup_hand(g, "scheme_counter")
		g.current = 1
		g.players[1].main = card("neutral_sword")
		check(g.submit(1, {"type":"attack", "target_slot":0}).is_empty(), "scheme base response")
		select(g, [response])
		if keep_plan: select(g, [], "base")
		check(g.players[0].hp == 12 and g.players[0].plan.is_empty() == not keep_plan, "base reduction preserves optional plan")
		g.dispose()

func zones_death_and_defense() -> void:
	var g := game()
	resonant(g, 0)
	var c := setup_plan(g, "scheme_supply")
	for i in range(8): setup_hand(g, "neutral_sword")
	check(g.submit(0, {"type":"end_turn"}).is_empty() and g.current == 1, "plan excluded from hand limit8")
	g.players[1].main = card("neutral_sword")
	check(g.submit(1, {"type":"attack", "target_slot":0}).is_empty(), "attack planner")
	check(g.pending.kind == "buffer" and g.find(g.pending.cards, c.id).is_empty(), "plan cannot buffer")
	drain(g)
	g.players[0].hp = 0
	g.refresh_winner()
	check(g.players[0].plan.is_empty() and not g.find(g.discard, c.id).is_empty(), "eliminated owner discards plan")
	g.refresh_winner()
	check(g.discard.filter(func(entry: Dictionary): return entry.id == c.id).size() == 1, "death cleanup does not duplicate plan")
	g.dispose()
	g = game()
	resonant(g, 2)
	setup_plan(g, "scheme_finale")
	g.players[1].hp = 0
	g.refresh_winner()
	begin(g)
	check(g.players[0].hand.size() == 4 and g.pending.is_empty() and g.players[0].plan.is_empty(), "no legal target skips damage but deep draw continues")
	g.dispose()
	g = game()
	resonant(g, 1)
	setup_plan(g, "scheme_detonate")
	g.players[1].res_once = 1
	g.players[1].damaged_by = [2, 3]
	begin(g)
	select(g, [], "1")
	check(g.players[1].hp == 10 and g.players[1].res_once == 0, "planned5 follows RES and third-attacker attenuation")
	g.dispose()
	g = game()
	resonant(g, 1)
	setup_plan(g, "scheme_detonate")
	g.players[1].main = card("forge_hammer")
	g.players[1].sub = card("forge_blade")
	var response := setup_hand(g, "forge_counter", 1)
	begin(g)
	select(g, [], "1")
	check(g.pending.kind != "counter", "attack-only counter cannot respond to planned damage")
	drain(g)
	g.dispose()

func run() -> void:
	restrictions()
	timing_and_targets()
	resonance_and_equipment()
	card_branches()
	immediate_resources()
	inspect_boundaries()
	counter_retrieval()
	zones_death_and_defense()
	print("PLANNING_TEST checks=%d failures=%d" % [checks, failures])
	quit(1 if failures > 0 else 0)
